output: array1.o arrayname2.o funcact.o funcact2.o

array1.o: array1.c
	gcc -o array1 array1.c

arrayname2.o: arrayname2.c
	gcc -o arrayname2 arrayname2.c

funcact.o: funcact.c
	gcc -o funcact funcact.c

funcact2.o: funcact2.c
	gcc -o funcact2 funcact2.c

clean:
	rm *.o *.err
