output: forkchildren5.o forkchildren2.o

forkchildren5.o: forkchildren5.c
	gcc -o forkchildren5 forkchildren5.c

forkchildren2.o: forkchildren2.c
	gcc -o forkchildren2 forkchildren2.c

clean:
	rm *.o *.err
