
output: branchloop.o branchloop2.o branchloop3.o
	
branchloop.o: branchloop.c
	gcc -o branchloop branchloop.c

branchloop2.o: branchloop2.c
	gcc -o brnachloop2 branchloop2.c

branchloop3.o: branchloop3.c
	gcc -o branchloop3 branchloop3.c

clean:
	rm *.o*.err   

